### ISSUE TITLE
Error webhook seems not working

### ISSUE THREAD

**Issue by 0x4B776F6B4353** [k3rn31p4nic/travis-ci-discord-webhook#6]
When Travis success , it works flawlessly. But when the build fails , it doesn't send

**Comment by k3rn31p4nic** [comment]
Can you send the build log? I can't say what's the issue without seeing the log, because it work's fine in my case: 
![image](https://user-images.githubusercontent.com/19631364/45586001-c01a4e00-b8de-11e8-8ad5-6a11f1cb3e10.png)

**Comment by rishav394** [comment]
Can you share your config @0x4B776F6B4353

**Comment by dhinakg** [comment]
Are you sure you have the after failure part as listed in the README.md, @0x4B776F6B4353?

**Comment by Incrested** [comment]
I have a similar issue. As you guys are looking for configs [here you go](https://github.com/KnoxDevTeam/Lavender/blob/master/.travis.yml)

**Comment by k3rn31p4nic** [comment]
@Incrested Can you send the build log as well?

**Comment by Incrested** [comment]
Yup, I put it [here](https://gist.github.com/Incrested/f547c84b0c6872e5a70793acd74b6c4e)

**Comment by k3rn31p4nic** [comment]
From your logs, it looks like the build was *stopped*, and therefore it never came to the `after_failure` part, and so the commands in the `after_failure` section didn't run.

The `after_failure` section will run only if the build *fails*, not if it was *stops*.

You can see an example of [a failed build here, that sends the failed webhook](https://travis-ci.org/TheBastionBot/Bastion/jobs/424211997).

**Comment by k3rn31p4nic** [comment]
Closing this issue because it has gone stale.
